name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3

#       - uses: actions/cache@v2
#         id: yarn-cache
#         with:
#           path: "node_modules"
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-
        
      - name: Install Dependencies
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      
      - name: Compile
        run: yarn build
      
      - name: echo ref
        run: echo ${{ github.ref }}
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          path: |
            dist
            firebase.json
            .firebaserc
  
#   deploy:
#     if: github.ref == 'refs/heads/master'
#     runs-on: ubuntu-latest
#     needs: [build]
#     steps:
#       - name: Download a Build Artifact
#         uses: actions/download-artifact@v2.0.5
                    
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v1.4.3
      
#       - name: Install firebase-tools
#         run: npm install -g firebase-tools
        
#       - name: Deploy to Firebase
#         working-directory: "artifact"
#         run: |
#           ls -al
#           firebase deploy --token $FIREBASE_TOKEN
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
          

      
